# Generated by Django 3.1 on 2020-08-25 06:33

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('PUB', 'Public'), ('TIME', 'Timed Release'), ('PRIV', 'Private List')], default='PRI', max_length=8)),
                ('release_time', models.DateTimeField(default=datetime.datetime.now)),
                ('whitelist', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
