# Generated by Django 3.0.8 on 2020-07-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubssmion',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
