# Generated by Django 3.0.8 on 2020-07-15 00:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0004_auto_20200712_1948'),
        ('submission', '0006_filesubssmion_problem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileSubssmion',
            new_name='FileSubmission',
        ),
    ]
