# Generated by Django 3.0.8 on 2020-08-09 07:16

from django.db import migrations, models
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20200715_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='random/'),
        ),
        migrations.AlterField(
            model_name='filesubmission',
            name='file',
            field=models.FileField(upload_to=submission.models.file_submission_name),
        ),
    ]
