# Generated by Django 3.0.8 on 2020-08-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20200809_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
