# Generated by Django 3.1 on 2020-08-25 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_add_visibility'),
        ('submission', '0010_auto_20200819_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='contest',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.contestmodel'),
        ),
    ]
