# Generated by Django 3.0.8 on 2020-07-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='problemtestmodel',
            name='unique task number',
        ),
        migrations.AddConstraint(
            model_name='problemtestmodel',
            constraint=models.UniqueConstraint(fields=('parent', 'task_num', 'sub_task_num'), name='unique task number'),
        ),
    ]
