# Generated by Django 3.0.8 on 2020-07-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20200711_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTestSuiteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_number', models.IntegerField(default=0)),
                ('test_suite_description', models.TextField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemModel')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemTestPairModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_number', models.IntegerField(default=0)),
                ('input', models.FileField(upload_to='')),
                ('output', models.FileField(upload_to='')),
                ('test_suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.ProblemTestSuiteModel')),
            ],
        ),
    ]
