# Generated by Django 3.0.8 on 2020-07-12 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_problemtestpairmodel_problemtestsuitemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemtestsuitemodel',
            old_name='suite_number',
            new_name='problem_suite_number',
        ),
    ]
