# Generated by Django 3.0.8 on 2020-07-15 07:37

from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20200712_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtestpairmodel',
            name='input',
            field=models.FileField(upload_to=problem.models.test_input_path),
        ),
        migrations.AlterField(
            model_name='problemtestpairmodel',
            name='output',
            field=models.FileField(upload_to=problem.models.test_expect_path),
        ),
    ]
