# Generated by Django 3.1 on 2020-08-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20200715_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemTestModel',
        ),
    ]
