# Generated by Django 3.1 on 2020-08-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20200819_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtestpairmodel',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
