# Generated by Django 3.1 on 2020-08-25 06:33

from django.db import migrations, models
import django.db.models.deletion


def set_visibility(apps, schema_editor):
    VisibilityModel = apps.get_model('visibility', 'VisibilityModel')
    ProblemModel = apps.get_model('problem', 'ProblemModel')
    for problem in ProblemModel.objects.all():
        new_visibility = VisibilityModel(mode='PUB')
        new_visibility.save()
        problem.visibility = new_visibility
        problem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_add_visibility'),
        ('visibility', '0001_add_visibility'),
        ('problem', '0008_problemtestpairmodel_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemmodel',
            name='contests',
            field=models.ManyToManyField(to='contest.ContestModel'),
        ),
        # apparently we have to do this to insert a new model for OneToOneField
        migrations.AddField(
            model_name='problemmodel',
            name='visibility',
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='visibility.visibilitymodel'),
            preserve_default=False,
        ),
        migrations.RunPython(set_visibility),
        migrations.AlterField(
            model_name='problemmodel',
            name='visibility',
            field=models.OneToOneField(
                null=False, on_delete=django.db.models.deletion.CASCADE, to='visibility.visibilitymodel'),
            preserve_default=False,
        ),
    ]
