# Generated by Django 3.1 on 2020-08-25 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visibility', '0001_add_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('authors', models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL)),
                ('contestants', models.ManyToManyField(related_name='contestant', to=settings.AUTH_USER_MODEL)),
                ('visibility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visibility.visibilitymodel')),
            ],
        ),
    ]
